### ISSUE TITLE
Property 'forRoot' does not exist on type 'typeof FacebookModule'.

### ISSUE THREAD

**Issue by n4jim** [greg-md/ng-facebook#1]
Hi i got this error:
Typescript Error
Property 'forRoot' does not exist on type 'typeof FacebookModule'.

@NgModule({
  imports: [
    BrowserModule,
    // 2. Register Facebook module with it's providers.
    [error here --> ]FacebookModule.forRoot()
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent]
})

how to resolve this ?

**Comment by greg-md** [comment]
Hi,

Looks like in Angular 4 something has changed. Last changes were made for Angular 2.

I created a fix and published a new version `1.0.12`, also updated the README.md.

Please update the package and import module without `.forRoot()`.

```typescript
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FacebookModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
