### ISSUE TITLE
(feature request): facebook login

### ISSUE THREAD

**Issue by moshejs** [greg-md/ng-facebook#2]
It would be cool if this library could allow for easy creation of facebook login. Thanks.

**Comment by greg-md** [comment]
Thank you @moshejs for the feature request. This is expected to be done in the next updates.

As soon as the library is using the main Facebook JS SDK, you have full access to all it's features.

**Comment by greg-md** [comment]
Added login support. https://github.com/greg-md/ng-facebook#login
